FROM python:3.12-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY data ./data
COPY models ./models
COPY src ./src

ENTRYPOINT ["python", "src/predict_cli.py"]
